config/routes.rb
Rails.application.routes.draw do
  get '/tasks/closed', to: 'tasks#closed_index', as: 'closed_tasks'
  resources :tasks
  post '/tasks/:id/close', to: 'tasks#close', as: 'close_task'
  post '/tasks/:id/reopen', to: 'tasks#reopen', as: 'reopen_task'
  root to: 'tasks#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'
end

app/models/task.rb
class Task < ActiveRecord::Base

  acts_as_taggable
  belongs_to :user

  validates :name, length: {maximum: 150}, presence: true
  validates :is_done, inclusion: { in: [true, false] }
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_tagger
  has_many :tasks, dependent: :destroy

  def self.create_with_omniauth(auth)
    where(provider: auth['provider'], uid: auth['uid']).first_or_create do |user|
      user.name = auth['info']['nickname']
    end
  end

  def owned_tag_list
    self.owned_tags.map do |tag|
      tag.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to :root  
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, notice: 'Sign out!!!!'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    if current_user
      @tasks = Task.where(is_done: false, user: current_user).order(:deadline)
      @task = Task.new
      @user_tags = current_user.owned_tag_list
    end
  end

  # TODO feature tag
  def closed_index
    @tasks = Task.where(is_done: true, user: current_user).order('updated_at DESC')
    @task = Task.new
    @user_tags = current_user.owned_tag_list
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.user = current_user
    if @task.save &&
        current_user.tag(@task, with: @task.tag_list.join(', '), on: :tags)
      flash[:notice] = 'タスクを作成しました'
      head 201
    else
      render json: {messages: @task.errors.full_messages}, status: 422
    end
  end

  # TODO feature tag
  def edit
    @task = Task.find(params[:id])
    if @task
      render json: {task: @task, tag:@task.tag_list}
    else
      render json: {messages: @task.errors.full_messages}, status: 422
    end
  end

  # TODO feature tag
  def update
    @task = Task.find(params[:id])
    if @task.update(task_params) &&
        current_user.tag(@task, with: @task.tag_list.join(', '), on: :tags)
      flash[:notice] = 'タスクを更新しました'
      head 201
    else
      render json: {messages: @task.errors.full_messages}, status: 422
    end
  end

  def close
    @task = Task.find(params[:id])
    if @task.update(is_done: true)
      render json: @task
    else
      render json: {messages: @task.errors.full_messages}, status: 422
    end
  end

  def reopen
    @task = Task.find(params[:id])
    if @task.update(is_done: false)
      render json: @task
    else
      render json: {messages: @task.errors.full_message}, status:422
    end
  end

  private
  def task_params
    params.require(:task).permit(
      :id, :name, :deadline, tag_list: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_close_icon
    haml_tag(:button, class: 'close', type: 'button', 'data-dismiss' => 'alert', 'aria-hidden' => 'true') do
      haml_concat '&times;'
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def panel_class_status(task)
    return 'panel-info' unless task.deadline

    sa = task.deadline.to_time - Time.now

    case sa.to_f / 3600
    when 72..Float::INFINITY then 'panel-primary'
    when 24..72 then 'panel-warning'
    else 'panel-danger'
    end
  end

  def create_google_calendar_link(task)
    "http://www.google.com/calendar/event?action=TEMPLATE&text=#{URI.escape(task.name)}&trp=false&sprop=name:TodoGrow"
    # &details='説明'
    # &location='場所'
    # &dates='20141007/20141008(この場合終日になる)'
    # &sprop=website:'リンク設置元のURL'
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "todogrow"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)

  %body
    %header.navbar.navbar-default{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{data: {toggle: 'collapse', target:'.navbar-responsive-collapse'}}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'TodoGrow', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'My Task', tasks_path
            %li
              = link_to 'Archive', closed_tasks_path
          %ul.nav.navbar-nav.navbar-right
            %li
              - if current_user
                = link_to 'Logout', logout_path
              - else
                = link_to 'Sign in/Sign up for Twitter', '/auth/twitter'

    .container#main-content
      - if flash[:notice]
        .alert.alert-success
          - alert_close_icon
          = flash[:notice]
      - if flash[:error]
        .alert.alert-danger
          - alert_close_icon
          = flash[:error]
      - if current_user
        = yield
      - else
        %h1 Sign In for Twitter
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/tasks/_form.html.haml
#task-modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data: {dismiss: 'modal'}, 'aria-hidden' => true}
          &times;
        %h4.modal-title
          Task
      = form_for(@task, remote: true, id: 'task-form') do |t|
        .modal-body
          .form-group.required
            = t.label :name, class: 'control-label'
            %span.control-label
              ( required )
            = t.text_field :name, class: 'form-control', id: 'task-name'
          .form-group
            = t.label :deadline, class: 'control-label'
            = t.text_field :deadline, id: 'datetimepicker', class: 'form-control', autocomplete: 'off', 'data-date-format' => "YYYY/MM/DD HH:mm"
            = t.hidden_field :id, id: 'task-id'
          .panel.panel-success.form-group
            .panel-heading
              = t.label :tag, class: 'control-label'
            #form-tags-list.panel-body
              %div{style: 'margin-bottom: 10px;'}
                %input.form-control{id: 'new-tag-text',type: 'text', name:'new-tag', style: 'width:50%;display:inline;'}
                %button.btn.btn-default{id: 'add-new-tag',type: 'button', data: {container: 'body', toggle: 'popover',placement: 'button'}}
                  +
              #enable-tag-list
                - @user_tags.each do |tag|
                  %input{id:"tag-#{tag}" ,name:'task[tag_list][]', type:'checkbox',value:"#{tag}", style:"display:none;"}
                  %label{for:"tag-#{tag}"}
                    %span.label.label-default.fa.pull-left.task-tag{style: 'margin-bottom:5px;'}
                      = "#{tag}"
        .modal-footer
          = t.submit nil, class: 'btn btn-lg btn-block btn-primary', data: {disable_with: 'in progress...'}

- content_for :page_javascript do
  :javascript
    $(function () {
      $('#datetimepicker').datetimepicker({
                icons: {
                    format: 'yyyy-mm-dd hh:ii',
                    language: 'ja',
                    time: "fa fa-clock-o",
                    date: "fa fa-calendar",
                    up: "fa fa-arrow-up",
                    down: "fa fa-arrow-down"
                }
            });
    });

app/views/tasks/closed_index.html.haml
%div.page-header
  %h1
    Archive
%div
  / = link_to('create task', new_task_path, class: 'btn btn-default btn-lg btn-block')
  %button#create-new-task.btn.btn-default.btn-lg.btn-block{data: {toggle: 'modal', target: '#task-modal'}}
    Create New Task
%hr

%div.list-group
  - @tasks.each do |task|
    %div.list-group-item{id: "task-#{task.id}"}
      %span.list-group-item-heading.lead
        = task.name
      = link_to 'OPEN', reopen_task_path(task.id), id: "reopen-task-#{task.id}", class: 'pull-right btn btn-danger btn-sm', method:'POST', remote: true, title: 'OPEN'
      %p.list-group-item-text
        = l task.updated_at, format: '%Y/%m/%d-%H:%M'
        done.
= render partial: "form", locals: {zone: @zone}

- content_for :page_javascript do
  :javascript
    $(function () {
      $('#datetimepicker').datetimepicker({
                icons: {
                    format: 'yyyy-mm-dd hh:ii',
                    language: 'ja',
                    time: "fa fa-clock-o",
                    date: "fa fa-calendar",
                    up: "fa fa-arrow-up",
                    down: "fa fa-arrow-down"
                }
            });
    });

app/views/tasks/index.html.haml
- if current_user
  = react_component('PageTitle', props={title: 'My Task'},)
  %div
    %button#create-new-task.btn.btn-default.btn-lg.btn-block{data: {toggle: 'modal', target: '#task-modal'}}
      Create New Task
  %hr

  %div.list-group
    - @tasks.each do |task|
      = react_component('TaskCard', props={task: task,
        status: panel_class_status(task),
        cal_url: create_google_calendar_link(task),
        edit_url: edit_task_path(task.id)})

  = render partial: "form", locals: {zone: @zone}